image: reg001.local:5000/shortishly/erlang-docker

before_script:
  - git config --global url.http://gitlab.dev.sunninghill.org/shortishly.insteadOf https://github.com/shortishly

stages:
  - build

app:
  stage: build
  script:
    - make
    - bin/mkimage
    - docker build --build-arg REL_NAME=$(bin/release_name) --build-arg ERTS_VSN=$(bin/system_version) --pull=true --no-cache=true --force-rm=true -t ${REGISTRY_HOST}/$(bin/release_name):$(bin/version) .
    - docker push ${REGISTRY_HOST}/$(bin/release_name):$(bin/version)
  only:
    - master
