image: reg001.local:5000/shortishly/erlang-docker

before_script:
  - git config --global url.http://gitlab.dev.sunninghill.org/shortishly.insteadOf https://github.com/shortishly

stages:
  - build

app:
  stage: build
  script:
    - make
    - bin/mkimage
    - docker build --build-arg REL_NAME=minerl --build-arg ERTS_VSN=7.3 --pull=true --no-cache=true --force-rm=true -t reg001.local:5000/shortishly/minerl .
    - docker push reg001.local:5000/shortishly/minerl
  only:
    - master
