image: reg001.local:5000/shortishly/erlang-docker

before_script:
  - git config --global url.http://gitlab.dev.sunninghill.org/shortishly.insteadOf https://github.com/shortishly

stages:
  - build

app:
  stage: build
  script:
    - make
    - bin/mkimage
  only:
    - master
